spring.application.name=agro-consorcio
server.servlet.context-path=/agro-consorcio

spring.datasource.url=jdbc:postgresql://localhost:5432/agro_consorcio
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

#rodar no celular
#server.address=0.0.0.0
#server.port=8080